version: '3'

services:
  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - 3001:3001
    restart: unless-stopped
    depends_on:
      - mongo-base

  mongo-base:
    container_name: mongo-app
    build:
      context: ./mongoose
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped
  
  
networks:
  app-network:
    driver: bridge